stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: 'Build'
    pool:
      vmImage: ubuntu-latest 
    steps:
    - script: echo Fake build code

- stage: Deploy
  displayName: 'Deploy'
  jobs:
  - job: 'Deploy'
    pool:
      vmImage: ubuntu-latest 
    steps:
    - script: echo Fake deploy code