stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - task: Docker@2
      displayName: dockerLogin
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnectionName)
    - task: Docker@2
      displayName: dockerBuild
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: $(dockerfile)
        tags: |
          $(imageTag)
- stage: Deploy
  displayName: 'Deploy'
  jobs:
  - job: 'Deploy'
    pool:
      vmImage: ubuntu-latest 
    steps:
    - script: echo Fake deploy code